version: "3"

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app/uploads:/app/app/uploads
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-dev_key_for_flask_app}
    restart: always
