version: "3"

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app/uploads:/app/app/uploads
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-dev_key_for_flask_app}
      - LLM_ENGINE=${LLM_ENGINE:-local}
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3:8b
    restart: always
    depends_on:
      - ollama

volumes:
  ollama_data:
